CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_FNL_LOAD`()
BEGIN

/*We wrote the logic for employee table where we are taking the data
from the hop1 table and manipulating the same as per the requriments
from the business*/

DECLARE SOURCE_TABLE VARCHAR(30);
DECLARE TARGET_TABLE VARCHAR(30);
DECLARE SOURCE_COUNT INT;
DECLARE TARGET_COUNT INT;
DECLARE PROCESS_NAME VARCHAR(30);
DECLARE OPEARATION_TYPE VARCHAR(100);
DECLARE LOG_DETAILS VARCHAR(100);

SELECT 'TBL_TRANS_EMPLOYEES_HOP2' INTO SOURCE_TABLE;
SELECT 'TBL_FNL_EMPLOYEES' INTO TARGET_TABLE;
SET OPEARATION_TYPE = 'LOADING THE FINAL EMPLOYEE TABLE';
SET PROCESS_NAME = 'SP_FNL_LOAD';

SELECT COUNT(*) INTO SOURCE_COUNT FROM TBL_TRANS_EMPLOYEES_HOP2;

INSERT INTO TBL_FNL_EMPLOYEES
SELECT *
FROM TBL_TRANS_EMPLOYEES_HOP2;


SELECT COUNT(*) INTO TARGET_COUNT FROM TBL_FNL_EMPLOYEES;


IF SOURCE_COUNT <> TARGET_COUNT THEN 
	SET LOG_DETAILS = 'THERE IS A MISMATCH, NEED TO CHECK THE FLOW';
ELSE 
	SET LOG_DETAILS = 'THERE IS NO MISMATCH, DATA LOADED SUCCESSFULLY';
END IF;



INSERT INTO HRDB_SYS_AUDIT_CONTROL
(SOURCE_NAME,
TARGET_NAME,
PROCESS_NAME,
OPERATION_TYPE,
SOURCE_COUNT,
TARGET_COUNT,
LOG_DETAILS,
OPERATED_BY,
OPERATION_DATE)
VALUES 
(SOURCE_TABLE,
TARGET_TABLE,
PROCESS_NAME,
OPEARATION_TYPE,
SOURCE_COUNT,
TARGET_COUNT,
LOG_DETAILS,
CURRENT_USER(),
CURRENT_TIMESTAMP()
);



/*DEPARTMENT TABLE LOAD*/

SELECT 'TBL_TRANS_DEPARTMENTS_HOP1' INTO SOURCE_TABLE;
SELECT 'TBL_FNL_DEPARTMENTS' INTO TARGET_TABLE;
SET OPEARATION_TYPE = 'LOADING THE FINAL DEPARTMENTS TABLE';
SET PROCESS_NAME = 'SP_FNL_LOAD';

SELECT COUNT(*) INTO SOURCE_COUNT FROM TBL_TRANS_DEPARTMENTS_HOP1;

INSERT INTO TBL_FNL_DEPARTMENTS
SELECT *
FROM TBL_TRANS_DEPARTMENTS_HOP1;


SELECT COUNT(*) INTO TARGET_COUNT FROM TBL_FNL_DEPARTMENTS;


IF SOURCE_COUNT <> TARGET_COUNT THEN 
	SET LOG_DETAILS = 'THERE IS A MISMATCH, NEED TO CHECK THE FLOW';
ELSE 
	SET LOG_DETAILS = 'THERE IS NO MISMATCH, DATA LOADED SUCCESSFULLY';
END IF;



INSERT INTO HRDB_SYS_AUDIT_CONTROL
(SOURCE_NAME,
TARGET_NAME,
PROCESS_NAME,
OPERATION_TYPE,
SOURCE_COUNT,
TARGET_COUNT,
LOG_DETAILS,
OPERATED_BY,
OPERATION_DATE)
VALUES 
(SOURCE_TABLE,
TARGET_TABLE,
PROCESS_NAME,
OPEARATION_TYPE,
SOURCE_COUNT,
TARGET_COUNT,
LOG_DETAILS,
CURRENT_USER(),
CURRENT_TIMESTAMP()
);

/*LOCATION TABLE LOAD*/

SELECT 'TBL_TRANS_LOCATIONS_HOP1' INTO SOURCE_TABLE;
SELECT 'TBL_FNL_LOCATIONS' INTO TARGET_TABLE;
SET OPEARATION_TYPE = 'LOADING THE FINAL LOCATIONS TABLE';
SET PROCESS_NAME = 'SP_FNL_LOAD';

SELECT COUNT(*) INTO SOURCE_COUNT FROM TBL_TRANS_LOCATIONS_HOP1;

INSERT INTO TBL_FNL_LOCATIONS
SELECT *
FROM TBL_TRANS_LOCATIONS_HOP1;


SELECT COUNT(*) INTO TARGET_COUNT FROM TBL_FNL_LOCATIONS;


IF SOURCE_COUNT <> TARGET_COUNT THEN 
	SET LOG_DETAILS = 'THERE IS A MISMATCH, NEED TO CHECK THE FLOW';
ELSE 
	SET LOG_DETAILS = 'THERE IS NO MISMATCH, DATA LOADED SUCCESSFULLY';
END IF;



INSERT INTO HRDB_SYS_AUDIT_CONTROL
(SOURCE_NAME,
TARGET_NAME,
PROCESS_NAME,
OPERATION_TYPE,
SOURCE_COUNT,
TARGET_COUNT,
LOG_DETAILS,
OPERATED_BY,
OPERATION_DATE)
VALUES 
(SOURCE_TABLE,
TARGET_TABLE,
PROCESS_NAME,
OPEARATION_TYPE,
SOURCE_COUNT,
TARGET_COUNT,
LOG_DETAILS,
CURRENT_USER(),
CURRENT_TIMESTAMP()
);


/*COUNTRY TABLE LOAD*/

SELECT 'TBL_STG_COUNTRIES' INTO SOURCE_TABLE;
SELECT 'TBL_FNL_COUNTRIES' INTO TARGET_TABLE;
SET OPEARATION_TYPE = 'LOADING THE FINAL COUNTRIES TABLE';
SET PROCESS_NAME = 'SP_FNL_LOAD';

SELECT COUNT(*) INTO SOURCE_COUNT FROM TBL_STG_COUNTRIES;

INSERT INTO TBL_FNL_COUNTRIES
SELECT *
FROM TBL_STG_COUNTRIES;


SELECT COUNT(*) INTO TARGET_COUNT FROM TBL_FNL_COUNTRIES;


IF SOURCE_COUNT <> TARGET_COUNT THEN 
	SET LOG_DETAILS = 'THERE IS A MISMATCH, NEED TO CHECK THE FLOW';
ELSE 
	SET LOG_DETAILS = 'THERE IS NO MISMATCH, DATA LOADED SUCCESSFULLY';
END IF;



INSERT INTO HRDB_SYS_AUDIT_CONTROL
(SOURCE_NAME,
TARGET_NAME,
PROCESS_NAME,
OPERATION_TYPE,
SOURCE_COUNT,
TARGET_COUNT,
LOG_DETAILS,
OPERATED_BY,
OPERATION_DATE)
VALUES 
(SOURCE_TABLE,
TARGET_TABLE,
PROCESS_NAME,
OPEARATION_TYPE,
SOURCE_COUNT,
TARGET_COUNT,
LOG_DETAILS,
CURRENT_USER(),
CURRENT_TIMESTAMP()
);

/*REGION TABLE LOAD*/

SELECT 'TBL_STG_REGIONS' INTO SOURCE_TABLE;
SELECT 'TBL_FNL_REGIONS' INTO TARGET_TABLE;
SET OPEARATION_TYPE = 'LOADING THE FINAL REGIONS TABLE';
SET PROCESS_NAME = 'SP_FNL_LOAD';

SELECT COUNT(*) INTO SOURCE_COUNT FROM TBL_STG_REGIONS;

INSERT INTO TBL_FNL_REGIONS
SELECT *
FROM TBL_STG_REGIONS;


SELECT COUNT(*) INTO TARGET_COUNT FROM TBL_FNL_REGIONS;


IF SOURCE_COUNT <> TARGET_COUNT THEN 
	SET LOG_DETAILS = 'THERE IS A MISMATCH, NEED TO CHECK THE FLOW';
ELSE 
	SET LOG_DETAILS = 'THERE IS NO MISMATCH, DATA LOADED SUCCESSFULLY';
END IF;



INSERT INTO HRDB_SYS_AUDIT_CONTROL
(SOURCE_NAME,
TARGET_NAME,
PROCESS_NAME,
OPERATION_TYPE,
SOURCE_COUNT,
TARGET_COUNT,
LOG_DETAILS,
OPERATED_BY,
OPERATION_DATE)
VALUES 
(SOURCE_TABLE,
TARGET_TABLE,
PROCESS_NAME,
OPEARATION_TYPE,
SOURCE_COUNT,
TARGET_COUNT,
LOG_DETAILS,
CURRENT_USER(),
CURRENT_TIMESTAMP()
);


/*JOBS TABLE LOAD*/

SELECT 'TBL_STG_JOBS' INTO SOURCE_TABLE;
SELECT 'TBL_FNL_JOBS' INTO TARGET_TABLE;
SET OPEARATION_TYPE = 'LOADING THE FINAL JOBS TABLE';
SET PROCESS_NAME = 'SP_FNL_LOAD';

SELECT COUNT(*) INTO SOURCE_COUNT FROM TBL_STG_JOBS;

INSERT INTO TBL_FNL_JOBS
SELECT *
FROM TBL_STG_JOBS;


SELECT COUNT(*) INTO TARGET_COUNT FROM TBL_FNL_JOBS;


IF SOURCE_COUNT <> TARGET_COUNT THEN 
	SET LOG_DETAILS = 'THERE IS A MISMATCH, NEED TO CHECK THE FLOW';
ELSE 
	SET LOG_DETAILS = 'THERE IS NO MISMATCH, DATA LOADED SUCCESSFULLY';
END IF;



INSERT INTO HRDB_SYS_AUDIT_CONTROL
(SOURCE_NAME,
TARGET_NAME,
PROCESS_NAME,
OPERATION_TYPE,
SOURCE_COUNT,
TARGET_COUNT,
LOG_DETAILS,
OPERATED_BY,
OPERATION_DATE)
VALUES 
(SOURCE_TABLE,
TARGET_TABLE,
PROCESS_NAME,
OPEARATION_TYPE,
SOURCE_COUNT,
TARGET_COUNT,
LOG_DETAILS,
CURRENT_USER(),
CURRENT_TIMESTAMP()
);

/*JOB_HISTORY TABLE LOAD*/

SELECT 'TBL_STG_JOB_HISTORY' INTO SOURCE_TABLE;
SELECT 'TBL_FNL_JOB_HISTORY' INTO TARGET_TABLE;
SET OPEARATION_TYPE = 'LOADING THE FINAL JOB_HIST TABLE';
SET PROCESS_NAME = 'SP_FNL_LOAD';

SELECT COUNT(*) INTO SOURCE_COUNT FROM TBL_STG_JOB_HISTORY;

INSERT INTO TBL_FNL_JOB_HISTORY
SELECT *
FROM TBL_STG_JOB_HISTORY;


SELECT COUNT(*) INTO TARGET_COUNT FROM TBL_FNL_JOB_HISTORY;


IF SOURCE_COUNT <> TARGET_COUNT THEN 
	SET LOG_DETAILS = 'THERE IS A MISMATCH, NEED TO CHECK THE FLOW';
ELSE 
	SET LOG_DETAILS = 'THERE IS NO MISMATCH, DATA LOADED SUCCESSFULLY';
END IF;



INSERT INTO HRDB_SYS_AUDIT_CONTROL
(SOURCE_NAME,
TARGET_NAME,
PROCESS_NAME,
OPERATION_TYPE,
SOURCE_COUNT,
TARGET_COUNT,
LOG_DETAILS,
OPERATED_BY,
OPERATION_DATE)
VALUES 
(SOURCE_TABLE,
TARGET_TABLE,
PROCESS_NAME,
OPEARATION_TYPE,
SOURCE_COUNT,
TARGET_COUNT,
LOG_DETAILS,
CURRENT_USER(),
CURRENT_TIMESTAMP()
);
END