CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_TRANS_HOP1_TO_HOP2`()
BEGIN

/*We wrote the logic for employee table where we are taking the data
from the hop1 table and manipulating the same as per the requriments
from the business*/

DECLARE SOURCE_TABLE VARCHAR(30);
DECLARE TARGET_TABLE VARCHAR(30);
DECLARE SOURCE_COUNT INT;
DECLARE TARGET_COUNT INT;
DECLARE PROCESS_NAME VARCHAR(30);
DECLARE OPEARATION_TYPE VARCHAR(100);
DECLARE LOG_DETAILS VARCHAR(100);

SELECT 'TBL_TRANS_EMPLOYEES_HOP1' INTO SOURCE_TABLE;
SELECT 'TBL_TRANS_EMPLOYEES_HOP2' INTO TARGET_TABLE;
SET OPEARATION_TYPE = 'ADDING THE COLUMNS AND VALUES FOR EMP';
SET PROCESS_NAME = 'SP_TRANS_HOP1_TO_HOP2';

SELECT COUNT(*) INTO SOURCE_COUNT FROM TBL_TRANS_EMPLOYEES_HOP1;

INSERT INTO TBL_TRANS_EMPLOYEES_HOP2
SELECT EMPLOYEE_ID,
CONCAT(FIRST_NAME,' ', LAST_NAME) EMPLOYEE_NAME,
EMAIL,
PHONE_NUMBER,
HIRE_DATE,
JOB_ID,
SALARY,
COMMISSION_PCT,
SALARY + (SALARY * COMMISSION_PCT) MONTHLY_SALARY,
CASE 
	WHEN SALARY>=2000 AND SALARY<=6000 THEN "Low Salary"
    WHEN SALARY>6000 AND SALARY <=10000 THEN "Average Salary"
    WHEN SALARY>10000 AND SALARY<=15000 THEN "High Salary"
    WHEN SALARY>15000 THEN "Very High Salary"
END SALARY_CATEGORY,
MANAGER_ID,
DEPARTMENT_ID
FROM TBL_TRANS_EMPLOYEES_HOP1;


SELECT COUNT(*) INTO TARGET_COUNT FROM TBL_TRANS_EMPLOYEES_HOP2;


IF SOURCE_COUNT <> TARGET_COUNT THEN 
	SET LOG_DETAILS = 'THERE IS A MISMATCH, NEED TO CHECK THE FLOW';
ELSE 
	SET LOG_DETAILS = 'THERE IS NO MISMATCH, DATA LOADED SUCCESSFULLY';
END IF;



INSERT INTO HRDB_SYS_AUDIT_CONTROL
(SOURCE_NAME,
TARGET_NAME,
PROCESS_NAME,
OPERATION_TYPE,
SOURCE_COUNT,
TARGET_COUNT,
LOG_DETAILS,
OPERATED_BY,
OPERATION_DATE)
VALUES 
(SOURCE_TABLE,
TARGET_TABLE,
PROCESS_NAME,
OPEARATION_TYPE,
SOURCE_COUNT,
TARGET_COUNT,
LOG_DETAILS,
CURRENT_USER(),
CURRENT_TIMESTAMP()
);

END